import { buttonVariants } from "@optima/ui/components/button";
import {
	Card,
	CardContent,
	CardHeader,
	CardTitle,
} from "@optima/ui/components/card";
import { cn } from "@optima/ui/lib/utils";
import Link from "next/link";

export default function PrivacyPage() {
	return (
		<div className="min-h-screen w-full space-y-2 p-4 mx-auto max-w-3xl pt-24">
			<h1 className="text-2xl font-bold text-center">Privacy Policy</h1>
			<p className="text-sm text-secondary-foreground text-center">
				Last updated: March 02, 2025
			</p>
			<div className="flex flex-col gap-8 pt-8">
				<div className="flex flex-col gap-2">
					<p>
						Staff Optima Inc ("us", "we", or "our") operates the Staff Optima
						application (hereinafter referred to as the "Service").
					</p>
					<p>
						This page informs you of our policies regarding the collection, use
						and disclosure of personal data when you use our Service and the
						choices you have associated with that data.
					</p>
					<p>
						We use your data to provide and improve the Service. By using the
						Service, you agree to the collection and use of information in
						accordance with this policy. Unless otherwise defined in this
						Privacy Policy, the terms used in this Privacy Policy have the same
						meanings as in our Terms and Conditions.
					</p>
				</div>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">Definitions</CardTitle>
					</CardHeader>
					<CardContent className="space-y-4">
						<div>
							<p className="font-semibold">Service</p>
							<p>
								Service is the Staff Optima application operated by Staff Optima
								Inc
							</p>
						</div>
						<div>
							<p className="font-semibold">Personal Data</p>
							<p>
								Personal Data means data about a living individual who can be
								identified from those data (or from those and other information
								either in our possession or likely to come into our possession).
							</p>
						</div>
						<div>
							<p className="font-semibold">Usage Data</p>
							<p>
								Usage Data is data collected automatically either generated by
								the use of the Service or from the Service infrastructure itself
								(for example, the duration of a page visit).
							</p>
						</div>
						<div>
							<p className="font-semibold">Cookies</p>
							<p>
								Cookies are small files stored on your device (computer or
								mobile device).
							</p>
						</div>
						<div>
							<p className="font-semibold">Data Controller</p>
							<p>
								Data Controller means the natural or legal person who (either
								alone or jointly or in common with other persons) determines the
								purposes for which and the manner in which any personal
								information are, or are to be, processed.
							</p>
							<p>
								For the purpose of this Privacy Policy, we are a Data Controller
								of your Personal Data.
							</p>
						</div>
						<div>
							<p className="font-semibold">
								Data Processors (or Service Providers)
							</p>
							<p>
								Data Processor (or Service Provider) means any natural or legal
								person who processes the data on behalf of the Data Controller.
							</p>
							<p>
								We may use the services of various Service Providers in order to
								process your data more effectively.
							</p>
						</div>
						<div>
							<p className="font-semibold">Data Subject (or User)</p>
							<p>
								Data Subject is any living individual who is using our Service
								and is the subject of Personal Data.
							</p>
						</div>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">
							Information Collection and Use
						</CardTitle>
					</CardHeader>
					<CardContent className="space-y-4">
						<p>
							We collect several different types of information for various
							purposes to provide and improve our Service to you.
						</p>

						<div>
							<p className="font-semibold">Types of Data Collected</p>

							<div className="mt-4">
								<p className="font-semibold">Personal Data</p>
								<p>
									While using our Service, we may ask you to provide us with
									certain personally identifiable information that can be used
									to contact or identify you ("Personal Data"). Personally
									identifiable information may include, but is not limited to:
								</p>
								<ul className="list-disc pl-6 mt-2">
									<li>Email address</li>
									<li>First name and last name, email and phone number</li>
									<li>Cookies and Usage Data</li>
								</ul>
								<p className="mt-2">
									We may use your Personal Data to contact you with newsletters,
									marketing or promotional materials and other information that
									may be of interest to you. You may opt out of receiving any,
									or all, of these communications from us by following the
									unsubscribe link or the instructions provided in any email we
									send.
								</p>
							</div>

							<div className="mt-4">
								<p className="font-semibold">Usage Data</p>
								<p>
									When you access the Service with a mobile device, we may
									collect certain information automatically, including, but not
									limited to, the type of mobile device you use, your mobile
									device unique ID, the IP address of your mobile device, your
									mobile operating system, the type of mobile Internet browser
									you use, unique device identifiers and other diagnostic data
									("Usage Data").
								</p>
							</div>

							<div className="mt-4">
								<p className="font-semibold">Tracking & Cookies Data</p>
								<p>
									We use cookies and similar tracking technologies to track the
									activity on our Service and we hold certain information.
								</p>
								<p>
									Cookies are files with a small amount of data which may
									include an anonymous unique identifier. Cookies are sent to
									your browser from a website and stored on your device. Other
									tracking technologies are also used such as beacons, tags and
									scripts to collect and track information and to improve and
									analyse our Service.
								</p>
								<p>
									You can instruct your browser to refuse all cookies or to
									indicate when a cookie is being sent. However, if you do not
									accept cookies, you may not be able to use some portions of
									our Service.
								</p>
								<p>Examples of Cookies we use:</p>
								<ul className="list-disc pl-6 mt-2">
									<li>
										<span className="font-semibold">Session Cookies.</span> We
										use Session Cookies to operate our Service.
									</li>
									<li>
										<span className="font-semibold">Preference Cookies.</span>{" "}
										We use Preference Cookies to remember your preferences and
										various settings.
									</li>
									<li>
										<span className="font-semibold">Security Cookies.</span> We
										use Security Cookies for security purposes.
									</li>
								</ul>
							</div>
						</div>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">Use of Data</CardTitle>
					</CardHeader>
					<CardContent>
						<p>
							Staff Optima Inc. uses the collected data for various purposes:
						</p>
						<ul className="list-disc pl-6 mt-2">
							<li>To provide and maintain our Service</li>
							<li>To notify you about changes to our Service</li>
							<li>
								To allow you to participate in interactive features of our
								Service when you choose to do so
							</li>
							<li>To provide customer support</li>
							<li>
								To gather analysis or valuable information so that we can
								improve our Service
							</li>
							<li>To monitor the usage of our Service</li>
							<li>To detect, prevent and address technical issues</li>
							<li>
								To provide you with news, special offers and general information
								about other goods, services and events which we offer that are
								similar to those that you have already purchased or enquired
								about unless you have opted not to receive such information
							</li>
						</ul>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">
							Legal Basis for Processing Personal Data under GDPR
						</CardTitle>
					</CardHeader>
					<CardContent className="space-y-4">
						<p>
							Staff Optima Inc. processes personal data based on applicable US
							laws, including but not limited to the California Consumer Privacy
							Act (CCPA) and the Children's Online Privacy Protection Act
							(COPPA) if applicable. We may also process personal data based on
							other legal grounds such as consent, contract necessity,
							legitimate interests, or compliance with legal obligations.
						</p>
						<p>
							If you are from the European Economic Area (EEA), Staff Optima
							Inc. legal basis for collecting and using the personal information
							described in this Privacy Policy depends on the Personal Data we
							collect and the specific context in which we collect it.
						</p>
						<p>Staff Optima Inc. may process your Personal Data because:</p>
						<ul className="list-disc pl-6">
							<li>We need to perform a contract with you</li>
							<li>You have given us permission to do so</li>
							<li>
								The processing is in our legitimate interests and it is not
								overridden by your rights
							</li>
							<li>For payment processing purposes</li>
							<li>To comply with the law</li>
						</ul>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">
							Retention of Data
						</CardTitle>
					</CardHeader>
					<CardContent className="space-y-4">
						<p>
							Staff Optima Inc. will retain your Personal Data only for as long
							as is necessary for the purposes set out in this Privacy Policy.
							We will retain and use your Personal Data to the extent necessary
							to comply with our legal obligations (for example, if we are
							required to retain your data to comply with applicable laws),
							resolve disputes and enforce our legal agreements and policies.
						</p>
						<p>
							Staff Optima Inc. will also retain Usage Data for internal
							analysis purposes. Usage Data is generally retained for a shorter
							period of time, except when this data is used to strengthen the
							security or to improve the functionality of our Service, or we are
							legally obligated to retain this data for longer periods.
						</p>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">
							Transfer of Data
						</CardTitle>
					</CardHeader>
					<CardContent className="space-y-4">
						<p>
							Your information, including Personal Data, may be transferred to,
							stored at, and processed in the United States, or other countries
							where Staff Optima Inc. or its affiliates, subsidiaries, or
							service providers maintain facilities.
						</p>
						<p>
							By using the Service, you consent to the transfer of your
							information to the United States or to any other country in which
							Staff Optima Inc. or its affiliates, subsidiaries, or service
							providers operate, and agree to the processing of your information
							as described in this Privacy Policy.
						</p>
						<p>
							Staff Optima Inc. will take all steps reasonably necessary to
							ensure that your data is treated securely and in accordance with
							this Privacy Policy and applicable data protection laws, including
							but not limited to the California Consumer Privacy Act (CCPA) and
							other relevant US regulations.
						</p>
						<p>
							For transfers of personal data from the European Economic Area
							(EEA) and Switzerland to the United States, Staff Optima Inc. may
							rely on appropriate safeguards, such as standard contractual
							clauses approved by the European Commission, adherence to the
							EU-U.S. Privacy Shield Framework, or other legal mechanisms
							permitted by applicable EEA and Swiss data protection laws.
						</p>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">
							Disclosure of Data
						</CardTitle>
					</CardHeader>
					<CardContent className="space-y-4">
						<div>
							<p className="font-semibold">Business Transaction</p>
							<p>
								If Staff Optima Inc. is involved in a merger, acquisition or
								asset sale, your Personal Data may be transferred. We will
								provide notice before your Personal Data is transferred and
								becomes subject to a different Privacy Policy.
							</p>
						</div>

						<div>
							<p className="font-semibold">Disclosure for Law Enforcement</p>
							<p>
								Under certain circumstances, Staff Optima Inc. may be required
								to disclose your Personal Data if required to do so by law or in
								response to valid requests by public authorities (e.g. a court
								or a government agency).
							</p>
						</div>

						<div>
							<p className="font-semibold">Legal Requirements</p>
							<p>
								Staff Optima Inc. may disclose your Personal Data in the good
								faith belief that such action is necessary to:
							</p>
							<ul className="list-disc pl-6 mt-2">
								<li>To comply with a legal obligation</li>
								<li>
									To protect and defend the rights or property of Staff Optima
									Inc.
								</li>
								<li>
									To prevent or investigate possible wrongdoing in connection
									with the Service
								</li>
								<li>
									To protect the personal safety of users of the Service or the
									public
								</li>
								<li>To protect against legal liability</li>
							</ul>
						</div>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">
							Security of Data
						</CardTitle>
					</CardHeader>
					<CardContent>
						<p>
							The security of your data is important to us but remember that no
							method of transmission over the Internet or method of electronic
							storage is 100% secure. While we strive to use commercially
							acceptable means to protect your Personal Data, we cannot
							guarantee its absolute security.
						</p>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">
							"Do Not Track" Signals
						</CardTitle>
					</CardHeader>
					<CardContent>
						<p>
							We do not support Do Not Track ("DNT"). Do Not Track is a
							preference you can set in your web browser to inform websites that
							you do not want to be tracked.
						</p>
						<p>
							You can enable or disable Do Not Track by visiting the Preferences
							or Settings page of your web browser.
						</p>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">
							Your Data Protection Rights
						</CardTitle>
					</CardHeader>
					<CardContent className="space-y-4">
						<p>
							If you are a resident of the United States, you may have certain
							data protection rights under applicable US laws, including but not
							limited to the California Consumer Privacy Act (CCPA) and other
							state laws regarding data protection and privacy rights. These
							rights may include:
						</p>
						<ul className="list-disc pl-6">
							<li>The right to access, update, or delete your information</li>
							<li>The right of rectification</li>
							<li>The right to object</li>
							<li>The right of restriction</li>
							<li>The right to data portability</li>
							<li>The right to withdraw consent</li>
						</ul>
						<p>
							Please note that we may ask you to verify your identity before
							responding to such requests.
						</p>

						<p>
							If you are a resident of the European Economic Area (EEA), you
							have additional data protection rights under the GDPR. Please
							contact us to exercise these rights.
						</p>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">
							Service Providers
						</CardTitle>
					</CardHeader>
					<CardContent className="space-y-4">
						<p>
							We may employ third party companies and individuals to facilitate
							our Service ("Service Providers"), provide the Service on our
							behalf, perform Service-related services or assist us in analyzing
							how our Service is used.
						</p>
						<p>
							These third parties have access to your Personal Data only to
							perform these tasks on our behalf and are obligated not to
							disclose or use it for any other purpose.
						</p>

						<div>
							<p className="font-semibold">Analytics</p>
							<p>
								We may use third-party Service Providers to monitor and analyse
								the use of our Service.
							</p>
						</div>

						<div>
							<p className="font-semibold">Payments</p>
							<p>
								We may provide paid products and/or services within the Service.
								In that case, we use third-party services for payment processing
								(e.g. payment processors).
							</p>
							<p>
								We will not store or collect your payment card details. That
								information is provided directly to our third-party payment
								processors whose use of your personal information is governed by
								their Privacy Policy.
							</p>
							<p>The payment processors we work with are:</p>
							<ul className="list-disc pl-6 mt-2">
								<li>
									<span className="font-semibold">Stripe</span>
									<br />
									Their Privacy Policy can be viewed at
									https://stripe.com/privacy
								</li>
							</ul>
						</div>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">
							Links to Other Sites
						</CardTitle>
					</CardHeader>
					<CardContent>
						<p>
							Our Service may contain links to other sites that are not operated
							by us. If you click a third party link, you will be directed to
							that third party's site. We strongly advise you to review the
							Privacy Policy of every site you visit.
						</p>
						<p>
							We have no control over and assume no responsibility for the
							content, privacy policies or practices of any third party sites or
							services.
						</p>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">
							Children's Privacy
						</CardTitle>
					</CardHeader>
					<CardContent className="space-y-4">
						<p>
							Our Service does not address anyone under the age of 18
							("Children").
						</p>
						<p>
							We do not knowingly collect personally identifiable information
							from anyone under the age of 18. If you are a parent or guardian
							and you are aware that your Child has provided us with Personal
							Data, please contact us. If we become aware that we have collected
							Personal Data from children without verification of parental
							consent, we take steps to remove that information from our
							servers.
						</p>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">
							Changes to This Privacy Policy
						</CardTitle>
					</CardHeader>
					<CardContent className="space-y-4">
						<p>
							We may update our Privacy Policy from time to time. We will notify
							you of any changes by posting the new Privacy Policy on this page.
						</p>
						<p>
							We will let you know via email and/or a prominent notice on our
							Service, prior to the change becoming effective and update the
							"effective date" at the top of this Privacy Policy.
						</p>
						<p>
							You are advised to review this Privacy Policy periodically for any
							changes. Changes to this Privacy Policy are effective when they
							are posted on this page.
						</p>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="text-lg font-bold">Contact Us</CardTitle>
					</CardHeader>
					<CardContent className="space-y-4">
						<p>
							If you have any questions about this Privacy Policy, please
							contact us:
						</p>
						<Link
							href="mailto:legal@staffoptima.co"
							className={cn(buttonVariants({ variant: "link" }), "!p-0")}
						>
							legal@staffoptima.co
						</Link>
					</CardContent>
				</Card>
			</div>
		</div>
	);
}
